### ISSUE TITLE
openssl error in tweet bot

### ISSUE THREAD

**Issue by emanuelfeld** [emanuelfeld/booksfordc#17]
```
Aug 11 22:55:12 booksfordc app/worker.1:  Traceback (most recent call last): 
Aug 11 22:55:12 booksfordc app/worker.1:    File "dcpl.py", line 150, in <module> 
Aug 11 22:55:12 booksfordc app/worker.1:      bot.run() 
Aug 11 22:55:12 booksfordc app/worker.1:    File "/app/.heroku/src/twitterbot/twitterbot/bot.py", line 384, in run 
Aug 11 22:55:12 booksfordc app/worker.1:      self._handle_mentions() 
Aug 11 22:55:12 booksfordc app/worker.1:    File "/app/.heroku/src/twitterbot/twitterbot/bot.py", line 241, in _handle_mentions 
Aug 11 22:55:12 booksfordc app/worker.1:      self.on_mention(mention, prefix) 
Aug 11 22:55:12 booksfordc app/worker.1:    File "dcpl.py", line 128, in on_mention 
Aug 11 22:55:12 booksfordc app/worker.1:      reply = search_dcpl(text) 
Aug 11 22:55:12 booksfordc app/worker.1:    File "dcpl.py", line 113, in search_dcpl 
Aug 11 22:55:12 booksfordc app/worker.1:      return search_sirsi(search) 
Aug 11 22:55:12 booksfordc app/worker.1:    File "dcpl.py", line 56, in search_sirsi 
Aug 11 22:55:12 booksfordc app/worker.1:      response = requests.get(search_url, allow_redirects=True) 
Aug 11 22:55:12 booksfordc app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 60, in get 
Aug 11 22:55:12 booksfordc app/worker.1:      return request('get', url, **kwargs) 
Aug 11 22:55:12 booksfordc app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 49, in request 
Aug 11 22:55:12 booksfordc app/worker.1:      return session.request(method=method, url=url, **kwargs) 
Aug 11 22:55:12 booksfordc app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 457, in request 
Aug 11 22:55:12 booksfordc app/worker.1:      resp = self.send(prep, **send_kwargs) 
Aug 11 22:55:12 booksfordc app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 595, in send 
Aug 11 22:55:12 booksfordc app/worker.1:      history = [resp for resp in gen] if allow_redirects else [] 
Aug 11 22:55:12 booksfordc app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 189, in resolve_redirects 
Aug 11 22:55:12 booksfordc app/worker.1:      allow_redirects=False, 
Aug 11 22:55:12 booksfordc app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 569, in send 
Aug 11 22:55:12 booksfordc app/worker.1:      r = adapter.send(request, **kwargs) 
Aug 11 22:55:12 booksfordc app/worker.1:    File "/app/.heroku/python/lib/python2.7/site-packages/requests/adapters.py", line 420, in send 
Aug 11 22:55:12 booksfordc app/worker.1:      raise SSLError(e, request=request) 
Aug 11 22:55:13 booksfordc app/worker.1:  requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) 
```

**Comment by ghost** [comment]
Issue still occuring?

**Comment by emanuelfeld** [comment]
Yup. Not really high priority, because it's not been used much. But if it's an easy fix, go ahead!
